Repository UDST/osmnet, pull requests merged in 2018-06, with the labels that each got.

#9 Re: suggested addition-argument for custom OSM filter
  osmnet/load.py
Labels: Type: new feature

#10 Code cleanup v0.1.5
  .coveragerc
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  HISTORY.rst
  README.rst
  docs/source/conf.py
  docs/source/installation.rst
  docs/source/introduction.rst
  docs/source/osmnet.rst
  osmnet/config.py
  osmnet/load.py
  osmnet/tests/test_config.py
  osmnet/tests/test_load.py
  osmnet/tests/test_utils.py
  osmnet/utils.py
  setup.py
Labels: Type: enhancement, Type: maintenance

#11 v0.1.5
  .coveragerc
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  HISTORY.rst
  README.rst
  docs/source/conf.py
  docs/source/installation.rst
  docs/source/introduction.rst
  docs/source/osmnet.rst
  osmnet/config.py
  osmnet/load.py
  osmnet/tests/test_config.py
  osmnet/tests/test_load.py
  osmnet/tests/test_utils.py
  osmnet/utils.py
  setup.py
Labels: Type: enhancement, Type: maintenance, Type: new feature
